import { redirect } from "next/dist/server/api-utils";
import Head from "next/head";
import Image from "next/image";
import Navigation from "../components/navigation/Navigation";

export default function Home() {
  return (
    <div>
      {/* <Head>
        <title>Moving Out </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className=" h-screen w-screen ">
          <Navigation />
          <h1 className={styles.title}>Welcome to Moving App</h1>
        </div>
      </main>

      <footer className={styles.footer}></footer> */}
    </div>
  );
}

export const getServerSideProps = async () => {
  return {
    props: {},
    redirect: {
      destination: "/home",
      permanent: false,
    },
  };
};
